# Generated by Django 2.2.8 on 2019-12-14 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import users.models.profile


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('language', models.TextField(choices=[('dk', 'Danish'), ('en', 'English')],
                                              default=users.models.profile.Languages('dk'), max_length=2)),
                ('profilepicture', models.ImageField(blank=True, null=True, upload_to='profilepictures')),
                ('profile_description', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile',
                                              to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_related_name': 'profile',
            },
        ),
    ]
