version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: pipenv run pip freeze | pipenv run manage.py migrate | python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=dev1234
      - POSTGRES_DB=meta_data_api

volumes:
  postgres_data:


