version: '3.7'

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=dev1234
      - POSTGRES_DB=meta_data_api
    ports:
      - 5432:5432
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  web:
    container_name: metadataapi_django
    build: .
    # runserver
    command: bash -c "python3 /code/manage.py migrate --noinput && python3 /code/manage.py runserver 0.0.0.0:80"
    # testing
    #command: bash -c "python3 /code/manage.py migrate --noinput && python3 /code/manage.py test"

    #    command: echo "django web has been disabled"
    volumes:
      - .:/code
    environment:
      - ENV=PROD
    ports:
      - "80:80"
    depends_on:
      - db
      - redis
  celery:
    build: .
    command: celery -A MetaDataApi worker -l info
    restart: on-failure
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
  celery-beat:
    build: .
    command: celery -A MetaDataApi beat -l DEBUG --scheduler django_celery_beat.schedulers:DatabaseScheduler
    restart: on-failure
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
  flower:  
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=8888
    ports:  
      - 8888:8888

volumes:
  postgres_data:


