version: '3.7'

services:
  db:
    container_name: metadataapi_db
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=dev1234
      - POSTGRES_DB=meta_data_api
    ports:
      - 5432:5432
  redis:
    container_name: metadataapi_redis
    image: "redis:alpine"
    ports:
      - 6379:6379
  web:
    container_name: metadataapi_django
    image: grusinator/meta-data-api
    volumes:
      - .:/code
    environment:
      - ENV
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
volumes:
  postgres_data:
  pgadmin_data:
networks:
  postgres:
    driver: bridge


