version: '3.7'

services:
  web:
    container_name: metadataapi_django2
    build:
      context: ../..
      dockerfile: devops/docker/app.Dockerfile
    volumes:
      - .:/code
    environment:
      - ENV
      - SECRET_KEY
    ports:
      - "80:80"
  db:
    container_name: postgres_db
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=dev1234
      - POSTGRES_DB=meta_data_api
    ports:
      - 5432:5432
volumes:
  postgres_data:
networks:
  postgres:
    driver: bridge


