version: '3.7'

services:
  db:
    container_name: metadataapi_db
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=dev1234
      - POSTGRES_DB=meta_data_api
  web:
    container_name: metadataapi_django
    build: ../..
    command: bash -c "python3 /code/manage.py migrate --noinput && python3 /code/manage.py runserver 0.0.0.0:80"
    volumes:
      - .:/code
    environment:
      - ENV
      - SECRET_KEY
    ports:
      - "80:80"
    depends_on:
      - db
      - redis
  extends:
    service: celery
    file: devops/docker/celery/docker-compose.celery.yml


volumes:
  postgres_data: