# Generated by Django 2.0.13 on 2019-12-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dynamic_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mutant_dynamic_models_person',
                'managed': False,
            },
        ),
    ]
