# Generated by Django 2.1.3 on 2018-11-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdPartyDataProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.TextField(unique=True)),
                ('api_type', models.TextField(choices=[('Oauth2-rest', 'Oauth2-rest'), ('Oauth2-graphql', 'Oauth2-graphql'), ('Token-rest', 'Token-rest')])),
                ('api_endpoint', models.TextField()),
                ('authorize_url', models.TextField()),
                ('access_token_url', models.TextField()),
                ('client_id', models.TextField()),
                ('client_secret', models.TextField()),
                ('scope', models.TextField()),
                ('redirect_uri', models.TextField()),
                ('rest_endpoints_list', models.TextField()),
                ('json_schema_file_url', models.TextField()),
            ],
        ),
    ]
