# Generated by Django 2.2.2 on 2019-06-09 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.TextField(unique=True)),
                ('api_endpoint', models.TextField()),
                ('authorize_url', models.TextField()),
                ('access_token_url', models.TextField()),
                ('client_id', models.TextField()),
                ('client_secret', models.TextField()),
                ('scope', models.TextField()),
                ('json_schema_file_url', models.TextField(blank=True, null=True)),
                ('data_provider_instance',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                   related_name='db_data_provider', to='metadata.Node')),
            ],
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('url', models.TextField()),
                ('api_type', models.TextField(choices=[('Oauth2-rest', 'OauthRest'), ('Oauth2-graphql', 'OauthGraphql'),
                                                       ('Token-rest', 'TokenRest')])),
                ('provider',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataproviders.DataProvider')),
            ],
        ),
        migrations.CreateModel(
            name='DataDump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('data', models.FileField(upload_to='')),
                ('endpoint',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataproviders.Endpoint')),
            ],
        ),
    ]
