# Generated by Django 2.1.7 on 2019-03-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dataproviders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thirdpartydataprovider',
            name='redirect_uri',
        ),
        migrations.AlterField(
            model_name='thirdpartydataprovider',
            name='json_schema_file_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
