# Generated by Django 2.1.2 on 2018-10-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataproviders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thirdpartydataprovider',
            old_name='redirect_url',
            new_name='redirect_uri',
        ),
        migrations.AlterField(
            model_name='thirdpartydataprovider',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
