# Generated by Django 2.2.2 on 2019-11-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dataproviders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataprovider',
            name='api_type',
            field=models.TextField(
                choices=[('OauthRest', 'OauthRest'), ('OauthGraphql', 'OauthGraphql'), ('TokenRest', 'TokenRest')],
                default='OauthRest'),
        ),
    ]
