# Generated by Django 2.2.2 on 2019-06-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dataproviders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataprovider',
            old_name='data_provider_instance',
            new_name='data_provider_node',
        ),
        migrations.RenameField(
            model_name='endpoint',
            old_name='name',
            new_name='endpoint_name',
        ),
        migrations.RenameField(
            model_name='endpoint',
            old_name='url',
            new_name='endpoint_url',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='api_type',
        ),
        migrations.AddField(
            model_name='dataprovider',
            name='api_type',
            field=models.TextField(
                choices=[('Oauth2-rest', 'OauthRest'), ('Oauth2-graphql', 'OauthGraphql'), ('Token-rest', 'TokenRest')],
                default='default'),
            preserve_default=False,
        ),
    ]
