# Generated by Django 2.2.2 on 2019-06-10 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dataproviders', '0002_auto_20190609_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datadump',
            old_name='date',
            new_name='date_downloaded',
        ),
        migrations.AlterField(
            model_name='datadump',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_dumps',
                                    to='dataproviders.Endpoint'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints',
                                    to='dataproviders.DataProvider'),
        ),
    ]
