# Generated by Django 2.1.2 on 2018-10-25 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataproviders', '0002_auto_20181024_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thirdpartydataprovider',
            old_name='name',
            new_name='provider_name',
        ),
    ]
