# Generated by Django 2.0.13 on 2019-12-10 10:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dataproviders', '0002_auto_20191112_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataprovider',
            name='data_provider_node',
        ),
    ]
