# Generated by Django 2.1.7 on 2019-03-24 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0003_auto_20190324_1156'),
        ('dataproviders', '0002_auto_20190323_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdpartydataprovider',
            name='data_provider_instance',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE,
                                    to='metadata.ObjectInstance'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thirdpartydataprovider',
            name='api_type',
            field=models.TextField(choices=[('Oauth2-rest', 'OauthRest'), ('Oauth2-graphql', 'OauthGraphql'),
                                            ('Token-rest', 'TokenRest')]),
        ),
    ]
