# Generated by Django 2.1.2 on 2018-10-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataproviders', '0003_auto_20181025_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdpartydataprovider',
            name='api_type',
            field=models.TextField(choices=[('Oauth2-rest', 'Oauth2-rest'), ('Oauth2-graphql', 'Oauth2-graphql'), ('Token-rest', 'Token-rest')], default='Oauth2-rest'),
            preserve_default=False,
        ),
    ]
