# Generated by Django 2.2.2 on 2019-06-10 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dataproviders', '0003_auto_20190610_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='OauthConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorize_url', models.TextField()),
                ('access_token_url', models.TextField()),
                ('client_id', models.TextField()),
                ('client_secret', models.TextField()),
                ('scope', models.TextField()),
                ('data_provider',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dataproviders.DataProvider')),
            ],
        ),
    ]
