# Generated by Django 2.1.7 on 2019-04-14 05:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_auto_20190324_1559'),
        ('metadata', '0004_auto_20190407_2001'),
        ('dataproviders', '0004_auto_20190324_1559'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ThirdPartyDataProvider',
            new_name='DataProvider',
        ),
    ]
