# Generated by Django 2.2.2 on 2019-06-10 08:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dataproviders', '0004_oauthconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataprovider',
            name='access_token_url',
        ),
        migrations.RemoveField(
            model_name='dataprovider',
            name='authorize_url',
        ),
        migrations.RemoveField(
            model_name='dataprovider',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='dataprovider',
            name='client_secret',
        ),
        migrations.RemoveField(
            model_name='dataprovider',
            name='json_schema_file_url',
        ),
        migrations.RemoveField(
            model_name='dataprovider',
            name='scope',
        ),
    ]
