# Generated by Django 2.1.7 on 2019-04-17 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dataproviders', '0005_auto_20190414_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataprovider',
            name='data_provider_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='db_data_provider', to='metadata.ObjectInstance'),
        ),
    ]
