# Generated by Django 2.2.2 on 2019-06-10 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dataproviders', '0005_auto_20190610_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthconfig',
            name='data_provider',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_config',
                                       to='dataproviders.DataProvider'),
        ),
    ]
