# Generated by Django 2.2.2 on 2019-06-10 09:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dataproviders', '0006_auto_20190610_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endpoint',
            old_name='provider',
            new_name='data_provider',
        ),
    ]
