# Generated by Django 2.2.2 on 2019-06-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dataproviders', '0007_auto_20190610_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datadump',
            old_name='data',
            new_name='file',
        ),
        migrations.AlterField(
            model_name='datadump',
            name='date_downloaded',
            field=models.DateField(auto_now=True),
        ),
    ]
