# Generated by Django 2.2.2 on 2019-06-10 17:22

from django.db import migrations, models

import MetaDataApi.metadata.custom_storages


class Migration(migrations.Migration):
    dependencies = [
        ('dataproviders', '0008_auto_20190610_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadump',
            name='file',
            field=models.FileField(storage=MetaDataApi.metadata.custom_storages.PrivateMediaStorage(),
                                   upload_to='datafiles/'),
        ),
    ]
