# Generated by Django 2.2.2 on 2019-06-12 15:51

import django.db.models.deletion
from django.db import migrations, models

import MetaDataApi.dataproviders.models.RequestType


class Migration(migrations.Migration):
    dependencies = [
        ('dataproviders', '0009_auto_20190610_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='request_type',
            field=models.TextField(
                choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'),
                         ('UPDATE', 'UPDATE')],
                default=MetaDataApi.dataproviders.models.RequestType.RequestType('GET')),
        ),
        migrations.AlterField(
            model_name='dataprovider',
            name='api_type',
            field=models.TextField(
                choices=[('OauthRest', 'OauthRest'), ('OauthGraphql', 'OauthGraphql'), ('TokenRest', 'TokenRest')],
                default='OauthRest'),
        ),
        migrations.CreateModel(
            name='HttpConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField()),
                ('url_encoded_params', models.TextField()),
                ('body_type', models.TextField()),
                ('body_content', models.TextField()),
                ('request_type', models.TextField()),
                ('data_provider',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='http_config',
                                      to='dataproviders.DataProvider')),
            ],
        ),
    ]
