# Generated by Django 2.2.2 on 2019-09-24 13:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dataproviders', '0011_auto_20190612_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataprovider',
            name='api_type',
            field=models.TextField(
                choices=[('OAUTH_REST', 'OauthRest'), ('OAUTH_GRAPHQL', 'OauthGraphql'), ('TOKEN_REST', 'TokenRest')],
                default='OauthRest'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='request_type',
            field=models.TextField(
                choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'),
                         ('UPDATE', 'UPDATE')], default='GET'),
        ),
        migrations.AlterField(
            model_name='httpconfig',
            name='body_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='httpconfig',
            name='body_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='httpconfig',
            name='request_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='httpconfig',
            name='url_encoded_params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
