# Generated by Django 2.2.2 on 2019-09-24 13:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dataproviders', '0012_auto_20190924_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='httpconfig',
            name='header',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
