# Generated by Django 2.2.5 on 2019-09-24 14:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dataproviders', '0014_auto_20190924_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='httpconfig',
            name='header',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='httpconfig',
            name='url_encoded_params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oauthconfig',
            name='scope',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
