# Generated by Django 2.2.5 on 2019-09-24 14:18

import djongo.models.json
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dataproviders', '0015_auto_20190924_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='httpconfig',
            name='header',
            field=djongo.models.json.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='httpconfig',
            name='url_encoded_params',
            field=djongo.models.json.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oauthconfig',
            name='scope',
            field=djongo.models.json.JSONField(),
        ),
    ]
