version: 2
jobs:
  build:
    working_directory: ~/MetaDataApi
    docker:
      - image: circleci/python:3.7
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=diable
      - image: nimbustech/postgres-ssl:9.5
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          TZ: "Etc/UTC" #"Europe/Copenhagen"
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.old.lock" }}
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
            sudo pip install coverage codacy-coverage
            pipenv run install -e git://github.com/grusinator/django-json2model#egg=django_json2model
            pipenv run install -e git://github.com/grusinator/django-generic-serializer#egg=django-generic-serializer
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.old.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"
      - run:
          command: |
            pipenv run python manage.py test
            coverage xml -i
            python-codacy-coverage -r coverage.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1