# Generated by Django 2.1.15 on 2020-02-06 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdfdatadump',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_fetches',
                                    to='metadata.Schema'),
        ),
    ]
