# Generated by Django 2.1.3 on 2018-11-24 08:12

import MetaDataApi.metadata.custom_storages
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('data_type', models.TextField(choices=[('datetime', 'datetime'), ('float', 'float'), ('int', 'int'), ('bool', 'bool'), ('string', 'string'), ('unknown', 'unknown')])),
                ('data_unit', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BoolAttributeInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField()),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boolattributeinstance', to='metadata.Attribute')),
            ],
            options={
                'abstract': False,
                'default_related_name': '%(model_name)s',
            },
        ),
        migrations.CreateModel(
            name='DateTimeAttributeInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DateTimeField()),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datetimeattributeinstance', to='metadata.Attribute')),
            ],
            options={
                'abstract': False,
                'default_related_name': '%(model_name)s',
            },
        ),
        migrations.CreateModel(
            name='FloatAttributeInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floatattributeinstance', to='metadata.Attribute')),
            ],
            options={
                'abstract': False,
                'default_related_name': '%(model_name)s',
            },
        ),
        migrations.CreateModel(
            name='ImageAttributeInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.ImageField(upload_to='')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imageattributeinstance', to='metadata.Attribute')),
            ],
            options={
                'abstract': False,
                'default_related_name': '%(model_name)s',
            },
        ),
        migrations.CreateModel(
            name='IntAttributeInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intattributeinstance', to='metadata.Attribute')),
            ],
            options={
                'abstract': False,
                'default_related_name': '%(model_name)s',
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectinstance', to='metadata.Object')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objectinstance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_related_name': '%(model_name)s',
            },
        ),
        migrations.CreateModel(
            name='ObjectRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('from_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_relations', to='metadata.Object')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectRelationInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectrelationinstance', to='metadata.ObjectRelation')),
                ('from_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_relations', to='metadata.ObjectInstance')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objectrelationinstance', to=settings.AUTH_USER_MODEL)),
                ('to_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_relations', to='metadata.ObjectInstance')),
            ],
            options={
                'default_related_name': '%(model_name)s',
            },
        ),
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField()),
                ('stoptime', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='datapoints/images')),
                ('audio', models.FileField(blank=True, null=True, upload_to='datapoints/audio')),
                ('value', models.FloatField(blank=True, null=True)),
                ('std', models.FloatField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RDFDataDump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('rdf_file', models.FileField(storage=MetaDataApi.metadata.custom_storages.MediaStorage(), upload_to='datapoints/audio')),
            ],
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(unique=True)),
                ('rdfs_file', models.FileField(blank=True, null=True, storage=MetaDataApi.metadata.custom_storages.MediaStorage(), upload_to='schemas')),
            ],
        ),
        migrations.CreateModel(
            name='StringAttributeInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stringattributeinstance', to='metadata.Attribute')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stringattributeinstance', to='metadata.ObjectInstance')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stringattributeinstance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'default_related_name': '%(model_name)s',
            },
        ),
        migrations.CreateModel(
            name='UnmappedObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('parrent_label', models.TextField()),
                ('childrens', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='rdfdatadump',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_dumps', to='metadata.Schema'),
        ),
        migrations.AddField(
            model_name='objectrelation',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_relations', to='metadata.Schema'),
        ),
        migrations.AddField(
            model_name='objectrelation',
            name='to_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_relations', to='metadata.Object'),
        ),
        migrations.AddField(
            model_name='object',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_list', to='metadata.Schema'),
        ),
        migrations.AddField(
            model_name='intattributeinstance',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intattributeinstance', to='metadata.ObjectInstance'),
        ),
        migrations.AddField(
            model_name='intattributeinstance',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intattributeinstance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imageattributeinstance',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imageattributeinstance', to='metadata.ObjectInstance'),
        ),
        migrations.AddField(
            model_name='imageattributeinstance',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imageattributeinstance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='floatattributeinstance',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floatattributeinstance', to='metadata.ObjectInstance'),
        ),
        migrations.AddField(
            model_name='floatattributeinstance',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floatattributeinstance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datetimeattributeinstance',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datetimeattributeinstance', to='metadata.ObjectInstance'),
        ),
        migrations.AddField(
            model_name='datetimeattributeinstance',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datetimeattributeinstance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boolattributeinstance',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boolattributeinstance', to='metadata.ObjectInstance'),
        ),
        migrations.AddField(
            model_name='boolattributeinstance',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boolattributeinstance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attribute',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='metadata.Object'),
        ),
        migrations.AlterUniqueTogether(
            name='objectrelationinstance',
            unique_together={('base', 'from_object', 'to_object')},
        ),
        migrations.AlterUniqueTogether(
            name='objectrelation',
            unique_together={('label', 'schema', 'from_object', 'to_object')},
        ),
        migrations.AlterUniqueTogether(
            name='object',
            unique_together={('label', 'schema')},
        ),
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together={('label', 'object')},
        ),
    ]
