# Generated by Django 2.2.2 on 2019-09-27 16:11

import MetaDataApi.metadata.custom_storages
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'default_related_name': '%(model_name)s',
            },
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(unique=True)),
                ('rdfs_file', models.FileField(blank=True, null=True, storage=MetaDataApi.metadata.custom_storages.PublicMediaStorage(), upload_to='schemas')),
            ],
        ),
        migrations.CreateModel(
            name='SchemaAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('data_type', models.TextField(choices=[('DateTime', 'DateTime'), ('Number', 'Number'), ('Integer', 'Integer'), ('Boolean', 'Boolean'), ('String', 'String'), ('File', 'File'), ('Image', 'Image'), ('Undefined', 'Undefined')])),
            ],
        ),
        migrations.CreateModel(
            name='UnmappedObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('parrent_label', models.TextField()),
                ('childrens', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StringAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stringattribute', to='metadata.SchemaAttribute')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stringattribute', to='metadata.Node')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stringattribute', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'default_related_name': '%(model_name)s',
            },
        ),
        migrations.CreateModel(
            name='SchemaNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schema_nodes', to='metadata.Schema')),
            ],
            options={
                'unique_together': {('label', 'schema')},
            },
        ),
        migrations.CreateModel(
            name='SchemaEdge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('from_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_edge', to='metadata.SchemaNode')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schema_edges', to='metadata.Schema')),
                ('to_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_edge', to='metadata.SchemaNode')),
            ],
            options={
                'unique_together': {('label', 'schema', 'from_object', 'to_object')},
            },
        ),
        migrations.AddField(
            model_name='schemaattribute',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='metadata.SchemaNode'),
        ),
        migrations.CreateModel(
            name='RDFDataDump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('rdf_file', models.FileField(storage=MetaDataApi.metadata.custom_storages.PrivateMediaStorage(), upload_to='datapoints/audio')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_dumps', to='metadata.Schema')),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='metadata.SchemaNode'),
        ),
        migrations.AddField(
            model_name='node',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='IntAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intattribute', to='metadata.SchemaAttribute')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intattribute', to='metadata.Node')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intattribute', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'default_related_name': '%(model_name)s',
            },
        ),
        migrations.CreateModel(
            name='ImageAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.ImageField(storage=MetaDataApi.metadata.custom_storages.PrivateMediaStorage(), upload_to='images')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imageattribute', to='metadata.SchemaAttribute')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imageattribute', to='metadata.Node')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imageattribute', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'default_related_name': '%(model_name)s',
            },
        ),
        migrations.CreateModel(
            name='FloatAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floatattribute', to='metadata.SchemaAttribute')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floatattribute', to='metadata.Node')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floatattribute', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'default_related_name': '%(model_name)s',
            },
        ),
        migrations.CreateModel(
            name='FileAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FileField(storage=MetaDataApi.metadata.custom_storages.PrivateMediaStorage(), upload_to='datafiles/')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fileattribute', to='metadata.SchemaAttribute')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fileattribute', to='metadata.Node')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fileattribute', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'default_related_name': '%(model_name)s',
            },
        ),
        migrations.CreateModel(
            name='DateTimeAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DateTimeField()),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datetimeattribute', to='metadata.SchemaAttribute')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datetimeattribute', to='metadata.Node')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datetimeattribute', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'default_related_name': '%(model_name)s',
            },
        ),
        migrations.CreateModel(
            name='BoolAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField()),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boolattribute', to='metadata.SchemaAttribute')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boolattribute', to='metadata.Node')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boolattribute', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'default_related_name': '%(model_name)s',
            },
        ),
        migrations.AlterUniqueTogether(
            name='schemaattribute',
            unique_together={('label', 'object')},
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='metadata.SchemaEdge')),
                ('from_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_edge', to='metadata.Node')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edge', to=settings.AUTH_USER_MODEL)),
                ('to_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_edge', to='metadata.Node')),
            ],
            options={
                'default_related_name': '%(model_name)s',
                'unique_together': {('base', 'from_object', 'to_object')},
            },
        ),
    ]
