# Generated by Django 2.1.2 on 2018-10-12 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ObjectInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_instances', to='metadata.Object')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectRelationInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_relation_instances', to='metadata.ObjectRelation')),
                ('from_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_relations', to='metadata.ObjectInstance')),
                ('to_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_relations', to='metadata.ObjectInstance')),
            ],
        ),
        migrations.AddField(
            model_name='attribute',
            name='dataunit',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attributeinstance',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_instances', to='metadata.Attribute'),
        ),
        migrations.AddField(
            model_name='attributeinstance',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='metadata.ObjectInstance'),
        ),
    ]
