# Generated by Django 2.1.7 on 2019-03-23 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from MetaDataApi.metadata.custom_storages import MediaStorage


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAttributeInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FileField(storage=MediaStorage(), upload_to='datafiles')),
                ('base',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fileattributeinstance',
                                   to='metadata.Attribute')),
                ('object',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fileattributeinstance',
                                   to='metadata.ObjectInstance')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                            related_name='fileattributeinstance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'default_related_name': '%(model_name)s',
            },
        ),
        migrations.AlterField(
            model_name='imageattributeinstance',
            name='value',
            field=models.ImageField(storage=MediaStorage(), upload_to='images'),
        ),
        migrations.AlterField(
            model_name='rdfdatadump',
            name='rdf_file',
            field=models.FileField(storage=MediaStorage(), upload_to='datapoints/audio'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='rdfs_file',
            field=models.FileField(blank=True, null=True, storage=MediaStorage(),
                                   upload_to='schemas'),
        ),
    ]
