# Generated by Django 2.0.13 on 2019-12-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemaattribute',
            name='data_type',
            field=models.TextField(choices=[('DateTime', 'DateTime'), ('Number', 'Number'), ('Integer', 'Integer'), ('Boolean', 'Boolean'), ('String', 'String'), ('File', 'File'), ('Undefined', 'Undefined')]),
        ),
    ]
