# Generated by Django 2.1.1 on 2018-09-17 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='attribute',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='metadata.Object'),
        ),
        migrations.AlterField(
            model_name='object',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='metadata.Schema'),
        ),
        migrations.AddField(
            model_name='objectrelation',
            name='from_object',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='to_relations', to='metadata.Object'),
        ),
        migrations.AddField(
            model_name='objectrelation',
            name='to_object',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='from_relations', to='metadata.Object'),
        ),
    ]
