# Generated by Django 2.1.7 on 2019-03-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0002_auto_20190323_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='data_unit',
            field=models.TextField(blank=True, null=True),
        ),
    ]
