# Generated by Django 2.1.1 on 2018-09-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_auto_20180917_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='name',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='object',
            old_name='name',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='objectrelation',
            old_name='name',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='schema',
            old_name='name',
            new_name='label',
        ),
        migrations.RemoveField(
            model_name='schema',
            name='origin',
        ),
        migrations.AddField(
            model_name='attribute',
            name='label',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objectrelation',
            name='label',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schema',
            name='url',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
