# Generated by Django 2.1.2 on 2018-10-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0003_auto_20181013_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='rdf_file',
            field=models.FileField(blank=True, null=True, upload_to='schemas'),
        ),
    ]
