# Generated by Django 2.1.7 on 2019-04-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0003_auto_20190324_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='data_unit',
        ),
        migrations.AlterField(
            model_name='attribute',
            name='data_type',
            field=models.TextField(
                choices=[('datetime', 'datetime'), ('float', 'float'), ('int', 'int'), ('bool', 'bool'),
                         ('string', 'string'), ('file', 'file'), ('image', 'image'), ('unknown', 'unknown')]),
        ),
    ]
