# Generated by Django 2.1.1 on 2018-09-18 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0003_auto_20180918_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objectrelation',
            old_name='description',
            new_name='url',
        ),
    ]
