# Generated by Django 2.1.7 on 2019-04-15 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0004_auto_20190407_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectinstance',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances',
                                    to='metadata.Object'),
        ),
        migrations.AlterField(
            model_name='objectrelationinstance',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances',
                                    to='metadata.ObjectRelation'),
        ),
    ]
