# Generated by Django 2.1.2 on 2018-10-15 12:46

import MetaDataApi.metadata.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0004_schema_rdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='rdf_file',
            field=models.FileField(blank=True, null=True, storage=MetaDataApi.metadata.storage.OverwriteStorage, upload_to='schemas'),
        ),
    ]
