# Generated by Django 2.1.7 on 2019-04-27 05:48

from django.db import migrations, models

import MetaDataApi.metadata.custom_storages


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0005_auto_20190415_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileattributeinstance',
            name='value',
            field=models.FileField(storage=MetaDataApi.metadata.custom_storages.PrivateMediaStorage(),
                                   upload_to='datafiles'),
        ),
        migrations.AlterField(
            model_name='imageattributeinstance',
            name='value',
            field=models.ImageField(storage=MetaDataApi.metadata.custom_storages.PrivateMediaStorage(),
                                    upload_to='images'),
        ),
        migrations.AlterField(
            model_name='rdfdatadump',
            name='rdf_file',
            field=models.FileField(storage=MetaDataApi.metadata.custom_storages.PrivateMediaStorage(),
                                   upload_to='datapoints/audio'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='rdfs_file',
            field=models.FileField(blank=True, null=True,
                                   storage=MetaDataApi.metadata.custom_storages.PublicMediaStorage(),
                                   upload_to='schemas'),
        ),
    ]
