# Generated by Django 2.1.2 on 2018-10-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0005_auto_20181015_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='rdf_file',
            field=models.FileField(blank=True, null=True, upload_to='schemas'),
        ),
    ]
