# Generated by Django 2.2 on 2019-05-04 14:14

from django.db import migrations, models

import MetaDataApi.metadata.custom_storages


class Migration(migrations.Migration):
    dependencies = [
        ('metadata', '0006_auto_20190427_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='data_type',
            field=models.TextField(
                choices=[('DateTime', 'DateTime'), ('Number', 'Number'), ('Integer', 'Integer'), ('Boolean', 'Boolean'),
                         ('String', 'String'), ('File', 'File'), ('Image', 'Image'), ('Undefined', 'Undefined')]),
        ),
        migrations.AlterField(
            model_name='fileattributeinstance',
            name='value',
            field=models.FileField(storage=MetaDataApi.metadata.custom_storages.PrivateMediaStorage(),
                                   upload_to='datafiles/'),
        ),
    ]
