# Generated by Django 2.1.2 on 2018-10-18 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0008_auto_20181016_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schema',
            old_name='rdf_file',
            new_name='rdfs_file',
        ),
    ]
