# Generated by Django 2.1.2 on 2018-10-20 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0009_auto_20181018_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributeinstance',
            name='base',
        ),
        migrations.RemoveField(
            model_name='attributeinstance',
            name='object',
        ),
        migrations.RemoveField(
            model_name='objectinstance',
            name='base',
        ),
        migrations.RemoveField(
            model_name='objectrelationinstance',
            name='base',
        ),
        migrations.RemoveField(
            model_name='objectrelationinstance',
            name='from_object',
        ),
        migrations.RemoveField(
            model_name='objectrelationinstance',
            name='to_object',
        ),
        migrations.DeleteModel(
            name='AttributeInstance',
        ),
        migrations.DeleteModel(
            name='ObjectInstance',
        ),
        migrations.DeleteModel(
            name='ObjectRelationInstance',
        ),
    ]
