# Generated by Django 2.1.2 on 2018-10-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0010_auto_20181020_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='datatype',
            field=models.TextField(choices=[('datetime', 'datetime'), ('float', 'float'), ('int', 'int'), ('bool', 'bool'), ('string', 'string'), ('unknown', 'unknown')]),
        ),
    ]
