# Generated by Django 2.1.2 on 2018-10-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0011_auto_20181027_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnmappedObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('parrent_label', models.TextField()),
                ('childrens', models.TextField()),
            ],
        ),
    ]
