# Generated by Django 2.1.2 on 2018-10-29 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0012_unmappedobject'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together={('label', 'object')},
        ),
        migrations.AlterUniqueTogether(
            name='object',
            unique_together={('label', 'schema')},
        ),
        migrations.AlterUniqueTogether(
            name='objectrelation',
            unique_together={('label', 'schema')},
        ),
        migrations.AlterUniqueTogether(
            name='schema',
            unique_together={('label', 'url')},
        ),
    ]
