# Generated by Django 2.1.3 on 2018-11-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0014_auto_20181109_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='unmappedobject',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
