# Generated by Django 2.1.3 on 2018-11-17 08:12

import MetaDataApi.metadata.custom_storages
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datapoints', '0012_auto_20181117_0912'),
        ('metadata', '0014_auto_20181109_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoolAttributeInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField()),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boolattributeinstance', to='metadata.Attribute')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boolattributeinstance', to='datapoints.ObjectInstance')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boolattributeinstance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_related_name': '%(model_name)s',
            },
        ),
        migrations.CreateModel(
            name='DateTimeAttributeInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DateTimeField()),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datetimeattributeinstance', to='metadata.Attribute')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datetimeattributeinstance', to='datapoints.ObjectInstance')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datetimeattributeinstance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_related_name': '%(model_name)s',
            },
        ),
        migrations.CreateModel(
            name='FloatAttributeInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floatattributeinstance', to='metadata.Attribute')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floatattributeinstance', to='datapoints.ObjectInstance')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floatattributeinstance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_related_name': '%(model_name)s',
            },
        ),
        migrations.CreateModel(
            name='ImageAttributeInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.ImageField(upload_to='')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imageattributeinstance', to='metadata.Attribute')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imageattributeinstance', to='datapoints.ObjectInstance')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imageattributeinstance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_related_name': '%(model_name)s',
            },
        ),
        migrations.CreateModel(
            name='IntAttributeInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intattributeinstance', to='metadata.Attribute')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intattributeinstance', to='datapoints.ObjectInstance')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intattributeinstance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_related_name': '%(model_name)s',
            },
        ),
        migrations.CreateModel(
            name='RDFDataDump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('rdf_file', models.FileField(storage=MetaDataApi.metadata.custom_storages.MediaStorage(), upload_to='datapoints/audio')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_dumps', to='metadata.Schema')),
            ],
        ),
        migrations.CreateModel(
            name='StringAttributeInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stringattributeinstance', to='metadata.Attribute')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stringattributeinstance', to='datapoints.ObjectInstance')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stringattributeinstance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_related_name': '%(model_name)s',
            },
        ),
        migrations.AddField(
            model_name='unmappedobject',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
