# Generated by Django 2.1.3 on 2018-11-17 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('metadata', '0015_auto_20181117_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectinstance', to='metadata.Attribute')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objectinstance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_related_name': '%(model_name)s',
            },
        ),
        migrations.CreateModel(
            name='ObjectRelationInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectrelationinstance', to='metadata.Attribute')),
                ('from_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_relations', to='metadata.ObjectInstance')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objectrelationinstance', to=settings.AUTH_USER_MODEL)),
                ('to_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_relations', to='metadata.ObjectInstance')),
            ],
            options={
                'default_related_name': '%(model_name)s',
            },
        ),
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField()),
                ('stoptime', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='datapoints/images')),
                ('audio', models.FileField(blank=True, null=True, upload_to='datapoints/audio')),
                ('value', models.FloatField(blank=True, null=True)),
                ('std', models.FloatField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='boolattributeinstance',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boolattributeinstance', to='metadata.ObjectInstance'),
        ),
        migrations.AlterField(
            model_name='datetimeattributeinstance',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datetimeattributeinstance', to='metadata.ObjectInstance'),
        ),
        migrations.AlterField(
            model_name='floatattributeinstance',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floatattributeinstance', to='metadata.ObjectInstance'),
        ),
        migrations.AlterField(
            model_name='imageattributeinstance',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imageattributeinstance', to='metadata.ObjectInstance'),
        ),
        migrations.AlterField(
            model_name='intattributeinstance',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intattributeinstance', to='metadata.ObjectInstance'),
        ),
        migrations.AlterField(
            model_name='stringattributeinstance',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stringattributeinstance', to='metadata.ObjectInstance'),
        ),
    ]
