# Generated by Django 2.1.3 on 2018-11-17 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0017_auto_20181117_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectinstance',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectinstance', to='metadata.Object'),
        ),
        migrations.AlterField(
            model_name='objectrelationinstance',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectrelationinstance', to='metadata.ObjectRelation'),
        ),
    ]
