# Generated by Django 2.1.3 on 2018-11-20 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0018_auto_20181117_1714'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='objectrelation',
            unique_together={('label', 'schema', 'from_object', 'to_object')},
        ),
    ]
