# Generated by Django 2.1.3 on 2018-11-20 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0019_auto_20181120_0743'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='objectrelationinstance',
            unique_together={('from_object', 'to_object')},
        ),
    ]
