# Generated by Django 2.1.3 on 2018-11-20 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0020_auto_20181120_0749'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='objectrelationinstance',
            unique_together={('base', 'from_object', 'to_object')},
        ),
    ]
