# Generated by Django 2.1 on 2018-09-04 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Datapoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('category', models.TextField(choices=[('TST', 'test'), ('SPC', 'speech_audio'), ('FOD', 'diet'), ('SLP', 'sleep'), ('PHY', 'physical_activity'), ('MEN', 'mental_activity'), ('BDY', 'body_measurement')], max_length=3)),
                ('image', models.ImageField(blank=True, null=True, upload_to='datapoints/images')),
                ('audio', models.FileField(blank=True, null=True, upload_to='datapoints/audio')),
                ('source_device', models.TextField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('text_from_audio', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DatapointV2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField()),
                ('stoptime', models.DateTimeField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('std', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField()),
                ('category', models.TextField(choices=[('TST', 'test'), ('SPC', 'speech_audio'), ('FOD', 'diet'), ('SLP', 'sleep'), ('PHY', 'physical_activity'), ('MEN', 'mental_activity'), ('BDY', 'body_measurement')], max_length=3)),
                ('label', models.TextField(max_length=20)),
                ('raw', models.BooleanField()),
                ('value_unit', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField()),
                ('stoptime', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='datapoints/images')),
                ('audio', models.FileField(blank=True, null=True, upload_to='datapoints/audio')),
                ('value', models.FloatField(blank=True, null=True)),
                ('std', models.FloatField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datapoints.MetaData')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='datapointv2',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datapoints.MetaData'),
        ),
        migrations.AddField(
            model_name='datapointv2',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
