# Generated by Django 2.1 on 2018-09-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapoints', '0002_auto_20180904_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='category',
            field=models.TextField(choices=[('test', 'test'), ('speech', 'speech'), ('diet', 'diet'), ('sleep', 'sleep'), ('phys_act', 'phys_act'), ('ment_act', 'ment_act'), ('body_meas', 'body_meas')], max_length=3),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='category',
            field=models.TextField(choices=[('test', 'test'), ('speech', 'speech'), ('diet', 'diet'), ('sleep', 'sleep'), ('phys_act', 'phys_act'), ('ment_act', 'ment_act'), ('body_meas', 'body_meas')], max_length=10),
        ),
    ]
