# Generated by Django 2.1.2 on 2018-10-19 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datapoints', '0003_auto_20180904_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapoint',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Datapoint',
        ),
    ]
