# Generated by Django 2.1.2 on 2018-10-20 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0010_auto_20181020_1202'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datapoints', '0004_auto_20181019_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericAttributeInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_instances', to='metadata.Attribute')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_instances', to='metadata.Object')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectRelationInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_relation_instances', to='metadata.ObjectRelation')),
                ('from_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_relations', to='datapoints.ObjectInstance')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('to_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_relations', to='datapoints.ObjectInstance')),
            ],
        ),
        migrations.CreateModel(
            name='TemporalFloatAttributeInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField()),
                ('stoptime', models.DateTimeField(blank=True, null=True)),
                ('value', models.FloatField()),
                ('std', models.FloatField(blank=True, null=True)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporal_float_attributes_insts', to='metadata.Attribute')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_float_attributes', to='datapoints.ObjectInstance')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TemporalStringAttributeInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField()),
                ('stoptime', models.DateTimeField(blank=True, null=True)),
                ('value', models.FloatField()),
                ('std', models.FloatField(blank=True, null=True)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporal_string_attribute_insts', to='metadata.Attribute')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_string_attributes', to='datapoints.ObjectInstance')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='genericattributeinstance',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='datapoints.ObjectInstance'),
        ),
    ]
