# Generated by Django 2.1.2 on 2018-10-20 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datapoints', '0005_auto_20181020_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapointv2',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='datapointv2',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='rawdata',
            name='metadata',
        ),
        migrations.DeleteModel(
            name='DatapointV2',
        ),
        migrations.DeleteModel(
            name='MetaData',
        ),
    ]
