# Generated by Django 2.1.2 on 2018-10-21 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0010_auto_20181020_1202'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datapoints', '0006_auto_20181020_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateTimeAttributeInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DateTimeField()),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datetime_attributes_insts', to='metadata.Attribute')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datetime_attributes', to='datapoints.ObjectInstance')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='floatattributeinstance',
            name='starttime',
        ),
        migrations.RemoveField(
            model_name='floatattributeinstance',
            name='stoptime',
        ),
        migrations.RemoveField(
            model_name='stringattributeinstance',
            name='starttime',
        ),
        migrations.RemoveField(
            model_name='stringattributeinstance',
            name='std',
        ),
        migrations.RemoveField(
            model_name='stringattributeinstance',
            name='stoptime',
        ),
        migrations.AlterField(
            model_name='floatattributeinstance',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='float_attributes_insts', to='metadata.Attribute'),
        ),
        migrations.AlterField(
            model_name='floatattributeinstance',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='float_attributes', to='datapoints.ObjectInstance'),
        ),
        migrations.AlterField(
            model_name='stringattributeinstance',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='string_attribute_insts', to='metadata.Attribute'),
        ),
        migrations.AlterField(
            model_name='stringattributeinstance',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='string_attributes', to='datapoints.ObjectInstance'),
        ),
        migrations.AlterField(
            model_name='stringattributeinstance',
            name='value',
            field=models.TextField(),
        ),
    ]
