# Generated by Django 2.1.2 on 2018-10-28 16:43

import MetaDataApi.metadata.custom_storages
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0012_unmappedobject'),
        ('datapoints', '0008_boolattributeinstance_intattributeinstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='RDFDataDump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('rdf_file', models.FileField(storage=MetaDataApi.metadata.custom_storages.MediaStorage(), upload_to='datapoints/audio')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_dumps', to='metadata.Schema')),
            ],
        ),
    ]
