# Generated by Django 2.1.3 on 2018-11-15 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0015_unmappedobject_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datapoints', '0011_baseattributeinstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAttributeInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.ImageField(upload_to='')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_attribute_insts', to='metadata.Attribute')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_attributes', to='datapoints.ObjectInstance')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='baseattributeinstance',
            name='base',
        ),
        migrations.RemoveField(
            model_name='baseattributeinstance',
            name='object',
        ),
        migrations.RemoveField(
            model_name='baseattributeinstance',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='genericattributeinstance',
            name='base',
        ),
        migrations.RemoveField(
            model_name='genericattributeinstance',
            name='object',
        ),
        migrations.RemoveField(
            model_name='genericattributeinstance',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='datetimeattributeinstance',
            name='base',
        ),
        migrations.RemoveField(
            model_name='floatattributeinstance',
            name='std',
        ),
        migrations.RemoveField(
            model_name='intattributeinstance',
            name='owner',
        ),
        migrations.AlterField(
            model_name='stringattributeinstance',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='string_instances', to='metadata.Attribute'),
        ),
        migrations.DeleteModel(
            name='BaseAttributeInstance',
        ),
        migrations.DeleteModel(
            name='GenericAttributeInstance',
        ),
    ]
