# Generated by Django 2.1.3 on 2018-11-17 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0016_auto_20181117_1153'),
        ('datapoints', '0012_auto_20181117_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectinstance',
            name='base',
        ),
        migrations.RemoveField(
            model_name='objectinstance',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='objectrelationinstance',
            name='base',
        ),
        migrations.RemoveField(
            model_name='objectrelationinstance',
            name='from_object',
        ),
        migrations.RemoveField(
            model_name='objectrelationinstance',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='objectrelationinstance',
            name='to_object',
        ),
        migrations.RemoveField(
            model_name='rawdata',
            name='owner',
        ),
        migrations.DeleteModel(
            name='ObjectInstance',
        ),
        migrations.DeleteModel(
            name='ObjectRelationInstance',
        ),
        migrations.DeleteModel(
            name='RawData',
        ),
    ]
