# Generated by Django 2.2.8 on 2019-12-14 10:46

import django.db.models.deletion
import generic_serializer.serializable_model
import jsonfield.fields
from django.conf import settings
from django.db import migrations, models

import MetaDataApi.custom_storages


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.TextField(unique=True)),
                ('api_type', models.TextField(
                    choices=[('rest', 'rest'), ('OauthGraphql', 'OauthGraphql'), ('TokenRest', 'TokenRest')],
                    default='rest')),
                ('api_endpoint', models.TextField()),
            ],
            bases=(models.Model, generic_serializer.serializable_model.SerializableModel),
        ),
        migrations.CreateModel(
            name='OauthConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorize_url', models.TextField()),
                ('access_token_url', models.TextField()),
                ('client_id', models.TextField()),
                ('client_secret', models.TextField()),
                ('scope', jsonfield.fields.JSONField()),
                ('data_provider',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_config',
                                      to='dataproviders.DataProvider')),
            ],
            bases=(models.Model, generic_serializer.serializable_model.SerializableModel),
        ),
        migrations.CreateModel(
            name='HttpConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', jsonfield.fields.JSONField(blank=True, null=True)),
                ('url_encoded_params', jsonfield.fields.JSONField(blank=True, null=True)),
                ('body_type', models.TextField(blank=True, null=True)),
                ('body_content', models.TextField(blank=True, null=True)),
                ('request_type', models.TextField(blank=True, null=True)),
                ('data_provider',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='http_config',
                                      to='dataproviders.DataProvider')),
            ],
            bases=(models.Model, generic_serializer.serializable_model.SerializableModel),
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_name', models.TextField()),
                ('endpoint_url', models.TextField()),
                ('request_type', models.TextField(
                    choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'),
                             ('UPDATE', 'UPDATE')], default='GET')),
                ('data_provider',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints',
                                   to='dataproviders.DataProvider')),
            ],
            bases=(models.Model, generic_serializer.serializable_model.SerializableModel),
        ),
        migrations.CreateModel(
            name='DataDump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_downloaded', models.DateField(auto_now=True)),
                ('file',
                 models.FileField(storage=MetaDataApi.custom_storages.PrivateMediaStorage(), upload_to='datafiles/')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_dumps',
                                               to='dataproviders.Endpoint')),
            ],
            bases=(models.Model, generic_serializer.serializable_model.SerializableModel),
        ),
        migrations.CreateModel(
            name='DataProviderUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('data_provider',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataproviders.DataProvider')),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_provider_users',
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('data_provider', 'user')},
            },
        ),
    ]
