# Generated by Django 2.1.15 on 2019-12-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dataproviders', '0002_datadump_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataprovideruser',
            name='data_fetching_is_active',
            field=models.BooleanField(default=True),
        ),
    ]
