# Generated by Django 2.1.15 on 2020-01-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dataproviders', '0003_dataprovideruser_data_fetching_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataprovideruser',
            name='expires_in',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataprovideruser',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataprovideruser',
            name='token_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
