# Generated by Django 2.1.15 on 2020-01-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dataproviders', '0004_auto_20200109_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataprovideruser',
            name='access_token',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dataprovideruser',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataprovideruser',
            name='token_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
