# Generated by Django 2.1.15 on 2020-02-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dataproviders', '0005_auto_20200109_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataprovider',
            name='icon_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
