# Generated by Django 2.1.15 on 2020-02-04 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import MetaDataApi.custom_storages


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataproviders', '0006_dataprovider_icon_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file',
                 models.FileField(storage=MetaDataApi.custom_storages.PrivateMediaStorage(), upload_to='datafiles/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('data_provider',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_uploads',
                                   to='dataproviders.DataProvider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
