# Generated by Django 2.1.15 on 2020-02-04 16:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataproviders', '0007_fileupload'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataDump',
            new_name='DataFetch',
        ),
    ]
