# Generated by Django 2.1.15 on 2020-02-06 10:30

import django.db.models.deletion
import jsonfield.fields
from django.conf import settings
from django.db import migrations, models

import MetaDataApi.custom_storages


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataproviders', '0008_auto_20200204_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now=True)),
                ('data_file',
                 models.FileField(storage=MetaDataApi.custom_storages.PrivateMediaStorage(), upload_to='datafiles/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataFileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file',
                 models.FileField(storage=MetaDataApi.custom_storages.PrivateMediaStorage(), upload_to='datafiles/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('data_provider',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_uploads',
                                   to='dataproviders.DataProvider')),
                ('refined_data_file',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_uploads',
                                   to='dataproviders.DataFile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='data_provider',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='user',
        ),
        migrations.RemoveField(
            model_name='datafetch',
            name='file',
        ),
        migrations.AddField(
            model_name='datafetch',
            name='parameters',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datafetch',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_fetches',
                                    to='dataproviders.Endpoint'),
        ),
        migrations.DeleteModel(
            name='FileUpload',
        ),
        migrations.AddField(
            model_name='datafetch',
            name='fetched_data_file',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE,
                                       related_name='data_fetches', to='dataproviders.DataFile'),
            preserve_default=False,
        ),
    ]
