# Generated by Django 2.1.15 on 2020-02-06 11:50

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import MetaDataApi.custom_storages


class Migration(migrations.Migration):
    dependencies = [
        ('dataproviders', '0009_auto_20200206_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datafetch',
            options={'default_related_name': '%(model_name)s'},
        ),
        migrations.AlterModelOptions(
            name='datafileupload',
            options={'default_related_name': '%(model_name)s'},
        ),
        migrations.RenameField(
            model_name='datafileupload',
            old_name='uploaded_file',
            new_name='data_file_from_source',
        ),
        migrations.RenameField(
            model_name='datafileupload',
            old_name='uploaded_at',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='datafetch',
            name='date_downloaded',
        ),
        migrations.RemoveField(
            model_name='datafetch',
            name='fetched_data_file',
        ),
        migrations.AddField(
            model_name='datafetch',
            name='data_file_from_source',
            field=models.FileField(default=None, storage=MetaDataApi.custom_storages.PrivateMediaStorage(),
                                   upload_to='datafiles/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datafetch',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datafetch',
            name='refined_data_file',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE,
                                       related_name='datafetch', to='dataproviders.DataFile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datafetch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datafetch',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='datafileupload',
            name='refined_data_file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datafileupload',
                                       to='dataproviders.DataFile'),
        ),
        migrations.AlterField(
            model_name='datafileupload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datafileupload',
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
