# Generated by Django 2.1.15 on 2020-02-06 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dataproviders', '0010_auto_20200206_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafetch',
            name='refined_data_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       related_name='datafetch', to='dataproviders.DataFile'),
        ),
        migrations.AlterField(
            model_name='datafileupload',
            name='refined_data_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       related_name='datafileupload', to='dataproviders.DataFile'),
        ),
    ]
