# Generated by Django 2.1.15 on 2020-02-06 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dataproviders', '0012_auto_20200206_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datafetch',
            options={'default_related_name': '%(model_name)s', 'verbose_name_plural': 'data_fetches'},
        ),
        migrations.AlterField(
            model_name='datafetch',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datafetch',
                                    to='dataproviders.Endpoint'),
        ),
    ]
