# Generated by Django 2.1.15 on 2020-02-09 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dataproviders', '0013_auto_20200206_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datafetch',
            options={'default_related_name': 'data_fetches', 'verbose_name_plural': 'data fetches'},
        ),
        migrations.AlterField(
            model_name='datafetch',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_fetches',
                                    to='dataproviders.Endpoint'),
        ),
        migrations.AlterField(
            model_name='datafetch',
            name='refined_data_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       related_name='data_fetches', to='dataproviders.DataFile'),
        ),
        migrations.AlterField(
            model_name='datafetch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_fetches',
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
