# Generated by Django 2.1.15 on 2020-02-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dataproviders', '0014_auto_20200209_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafetch',
            name='has_been_refined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datafileupload',
            name='has_been_refined',
            field=models.BooleanField(default=False),
        ),
    ]
