# Generated by Django 2.1.15 on 2020-02-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dataproviders', '0016_auto_20200211_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataprovider',
            name='api_type',
        ),
        migrations.AddField(
            model_name='dataprovider',
            name='provider_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='api_type',
            field=models.CharField(
                choices=[('OauthRest', 'OauthRest'), ('OauthGraphql', 'OauthGraphql'), ('TokenRest', 'TokenRest')],
                default='OauthRest', max_length=15),
        ),
        migrations.AlterField(
            model_name='dataprovider',
            name='api_endpoint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='request_type',
            field=models.CharField(
                choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'),
                         ('UPDATE', 'UPDATE')], default='GET', max_length=10),
        ),
    ]
