# Generated by Django 2.1.15 on 2020-02-20 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dataproviders', '0018_datafile_data_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafetch',
            name='data_provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='data_fetches',
                                    to='dataproviders.DataProvider'),
            preserve_default=False,
        ),
    ]
