# Generated by Django 2.1.15 on 2020-02-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dataproviders', '0019_datafetch_data_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataprovider',
            name='api_endpoint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataprovider',
            name='provider_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
