# Generated by Django 2.1.15 on 2020-02-27 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dataproviders', '0020_auto_20200220_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataprovideruser',
            options={'default_related_name': 'data_provider_users'},
        ),
        migrations.AlterField(
            model_name='dataprovideruser',
            name='data_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_provider_users',
                                    to='dataproviders.DataProvider'),
        ),
    ]
