# Generated by Django 2.1.15 on 2020-05-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dataproviders', '0021_auto_20200227_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='requires_auth',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='endpoint_name',
            field=models.TextField(max_length=50),
        ),
    ]
