# Generated by Django 2.1.15 on 2020-05-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dataproviders', '0023_auto_20200530_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='api_type',
            field=models.CharField(choices=[('rest', 'rest'), ('graphql', 'graphql')], default='rest', max_length=10,
                                   null=True),
        ),
    ]
