# Generated by Django 2.1.15 on 2020-05-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dataproviders', '0025_auto_20200530_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='api_type',
            field=models.CharField(blank=True, choices=[('rest', 'rest'), ('graphql', 'graphql')], default='rest',
                                   max_length=10, null=True),
        ),
    ]
