# Generated by Django 2.1.15 on 2020-05-30 15:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dataproviders', '0027_auto_20200530_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endpoint',
            name='auth_type',
        ),
    ]
