# Generated by Django 2.1.15 on 2020-05-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dataproviders', '0028_remove_endpoint_auth_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='auth_type',
            field=models.CharField(blank=True, choices=[('token', 'token'), ('oauth2', 'oauth2'), (None, None)],
                                   default=None, max_length=10, null=True),
        ),
    ]
