# Generated by Django 2.1.15 on 2020-05-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dataproviders', '0029_endpoint_auth_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='api_type',
            field=models.CharField(choices=[('rest', 'rest'), ('graphql', 'graphql')], default='rest', max_length=10),
        ),
    ]
