# Generated by Django 2.1.15 on 2020-05-30 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dataproviders', '0030_auto_20200530_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenUrlArg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'UrlArg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UrlArg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value_type', models.CharField(max_length=50)),
                ('endpoint',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataproviders.Endpoint')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
