# Generated by Django 2.1.15 on 2020-05-31 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dataproviders', '0031_tokenurlarg_urlarg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlarg',
            old_name='key',
            new_name='key_name',
        ),
        migrations.RemoveField(
            model_name='urlarg',
            name='value_type',
        ),
        migrations.AddField(
            model_name='urlarg',
            name='arg_type',
            field=models.CharField(
                choices=[('AuthToken', 'AuthToken'), ('StartDateTime', 'StartDateTime'), ('EndDateTime', 'EndDateTime'),
                         ('PageCurrent', 'PageCurrent'), ('PageSize', 'PageSize')], default='AuthToken', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urlarg',
            name='value_formatter',
            field=models.CharField(choices=[(None, None), ('TimeUtcSec', 'TimeUtcSec'), ('TimeYMD', 'TimeYMD')],
                                   default=None, max_length=50),
            preserve_default=False,
        ),
    ]
