# Generated by Django 2.1.15 on 2020-05-31 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dataproviders', '0032_auto_20200531_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlarg',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url_args',
                                    to='dataproviders.Endpoint'),
        ),
        migrations.AlterField(
            model_name='urlarg',
            name='value_formatter',
            field=models.CharField(choices=[(None, None), ('TimeUtcSec', 'TimeUtcSec'), ('TimeYMD', 'TimeYMD')],
                                   default=None, max_length=50, null=True),
        ),
    ]
