# Generated by Django 2.1.15 on 2020-05-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dataproviders', '0033_auto_20200531_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlarg',
            name='value_formatter',
            field=models.CharField(blank=True,
                                   choices=[(None, None), ('TimeUtcSec', 'TimeUtcSec'), ('TimeYMD', 'TimeYMD')],
                                   default=None, max_length=50, null=True),
        ),
    ]
