# Generated by Django 2.1.15 on 2020-06-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dataproviders', '0034_auto_20200531_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='data_structure_root',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
