# Generated by Django 2.2.2 on 2019-09-27 08:38

import MetaDataApi.users.models.profile
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataproviders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('language', models.TextField(choices=[('dk', 'Danish'), ('en', 'English')], default=MetaDataApi.users.models.profile.Languages('dk'), max_length=2)),
                ('profilepicture', models.ImageField(blank=True, null=True, upload_to='profilepictures')),
                ('audio_threshold', models.FloatField(blank=True, default=3.0, null=True)),
                ('profile_description', models.TextField(blank=True, null=True)),
                ('foaf_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='metadata.Node')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_related_name': 'profile',
            },
        ),
        migrations.CreateModel(
            name='DataProviderProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('data_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataproviders.DataProvider')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_provider_profiles', to='users.Profile')),
            ],
            options={
                'unique_together': {('data_provider', 'profile')},
            },
        ),
    ]
