# Generated by Django 2.1.2 on 2018-10-23 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdpartyprofile',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataproviders.ThirdPartyDataProvider'),
        ),
    ]
