# Generated by Django 2.1.2 on 2018-10-25 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181024_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdpartyprofile',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_provider_profiles', to='users.Profile'),
        ),
    ]
