# Generated by Django 2.1.7 on 2019-04-14 05:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dataproviders', '0005_auto_20190414_0722'),
        ('users', '0003_auto_20190324_1559'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ThirdPartyProfile',
            new_name='DataProviderProfile',
        ),
    ]
