# Generated by Django 2.1.2 on 2018-10-29 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataproviders', '0004_thirdpartydataprovider_api_type'),
        ('users', '0004_auto_20181025_0825'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='thirdpartyprofile',
            unique_together={('provider', 'profile')},
        ),
    ]
