# Generated by Django 2.1.7 on 2019-04-15 20:46

from django.db import migrations, models

import MetaDataApi.users.models.profile


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_auto_20190414_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='audio_threshold',
            field=models.FloatField(blank=True, default=3.0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.TextField(choices=[('dk', 'Danish'), ('en', 'English')],
                                   default=MetaDataApi.users.models.profile.Languages('dk'), max_length=2),
        ),
    ]
