# Generated by Django 2.1.15 on 2019-12-16 07:58

import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_name', models.TextField()),
                ('json_data', jsonfield.fields.JSONField()),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
