# Generated by Django 2.1.15 on 2020-01-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dynamic_models', '0002_auto_20191221_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dummy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
    ]
