# Generated by Django 2.1.15 on 2020-02-20 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dynamic_models', '0004_dynamicmetaobject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dynamicmetaobject',
            options={'default_related_name': 'dynamic_meta_objects'},
        ),
        migrations.AlterField(
            model_name='dynamicmetaobject',
            name='data_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_meta_objects',
                                    to='dataproviders.DataProvider'),
        ),
        migrations.AlterField(
            model_name='dynamicmetaobject',
            name='dynamic_model',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_meta_objects',
                                       to='mutant.ModelDefinition'),
        ),
    ]
